### ISSUE TITLE
porter bundle permission issue

### ISSUE THREAD

**Issue by rzhang628** [Azure/azure-service-operator-porter#3]
tried to publish bundle in aksmcrimagescommon.azurecr.io/public/aks/porter/azure-service-operator:v0.0.1, and got the errors as below: 

Error: unable to pull bundle before invoking credentials generate: unable to pull bundle aksmcrimagescommon.azurecr.io/public/aks/porter/azure-service-operator:v0.0.1: unable to pull remote bundle: failed to resolve bundle manifest "aksmcrimagescommon.azurecr.io/public/aks/porter/azure-service-operator:v0.0.1": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized

**Comment by Tatsinnit** [comment]
Thank you for jumping on a quick call Rong, So glad we caught this. Closing this issues as changing it to `aksrepos` temporarily fixes the issue. I am creating web hook for `aksmcrimagescommon` hoping that will resolve this permission issue. Thanks,
